### PR TITLE
fix: Fix skipping ahead via upgrading OpenMPT to 0.7.0 (#52)

### LINKED ISSUE #52: Unable to skip ahead in track
I'm back with probably what's another edge-case issue.

Playing [track id 138328](https://coolmodfiles.com/?trackId=138328), you can not skip ahead further into the track. Attempting to do so ends the track and loads a new one - unless one has repeat turned on, in which case it will just not skip ahead and do a weird echo (double playing every note) for the duration of a single pattern before fixing itself. I don't know if this has something to do with libopenmpt handling .xm files, but I don't remember all .xm files doing this, just this specific track.

Here is the details in bullet list form, for further clarification:
- You can skip backwards. If the current playing time is 01:00, you can skip back to 00:30.
- You can not skip forwards. If the current playing time is 01:00, and you attempt to skip to 01:30, it fails.
- If you wait until the song plays to 02:00, and try to skip to 01:30, it works.
- Track id 138328 is the only instance of this occuring that I know of.
- Big player or compact player mode doesn't matter.

My browser is Mozilla Firefox, if that matters.

### PR DESCRIPTION
**Pull request by Cthulhu2**
OpenMPT Lib v0.5.1 -> v0.7.0
OpenMPT Core v1.41.1.2 -> v1.49.0.19

fixes #52

### CODE REVIEW

**Comment by orhun** [comment]
Great PR, thanks for this! 💖

Calling out @WKFO for testing, it is a core library so we need to make sure everything works properly.

See the preview here: https://cool-mod-files-git-fork-cthulhu2-fix-skip-ahead-52-orhun.vercel.app/

**Comment by Cthulhu2** [comment]
I did try to build `libopenmpt`, but it crashed on `_openmpt_module_create_from_memory`. May be it was an unstable branch... Finally, I tumbled to check out the modarchive.org. The `libopenmpt` from this urls:
* https://modarchive.org/style/js/libopenmpt.wasm
* https://modarchive.org/style/js/libopenmpt.js

**Comment by orhun** [comment]
So are we using the same libopenmpt as modarchive?

**Comment by Cthulhu2** [comment]
Yes.
```
$ wget https://modarchive.org/style/js/libopenmpt.js
...
$ sha256sum ./libopenmpt.js 
95abd981c41474e2f0a08f74619cd83c59fc30883426fdbd0b7ddfdde953de51  ./libopenmpt.js
$ sha256sum ./public/libopenmpt.js 
95abd981c41474e2f0a08f74619cd83c59fc30883426fdbd0b7ddfdde953de51  ./public/libopenmpt.js

$ wget https://modarchive.org/style/js/libopenmpt.wasm
...
$ sha256sum ./libopenmpt.wasm 
c52f1143ae789e2a7222259951c0785fca89fd821f0c153cb1617b574fb26b73  ./libopenmpt.wasm
$ sha256sum ./public/bin/libopenmpt.wasm 
c52f1143ae789e2a7222259951c0785fca89fd821f0c153cb1617b574fb26b73  ./public/bin/libopenmpt.wasm
```

**Review by WKFO — APPROVED** [review]
Seems to have fixed the skipping problem. That's all I can say by testing, on the surface. Nice work.

**Review by orhun — APPROVED** [review]

**Review by orhun — APPROVED** [review]

**Pull request merged**
