### PR TITLE
feat: Add volume adjust to player

### PR DESCRIPTION
**Pull request by Cthulhu2**

### CODE REVIEW

**Review by bufgix — APPROVED** [review]
💯

**Comment by WKFO** [comment]
Very nice! One suggestion though. Could we move the slider over to the left hand side like this? Just so it doesn't get confusing with two horizontal sliders. (PS. the icon isn't a necessity for now)
id
:

**Review by WKFO — APPROVED** [review]

**Comment by Cthulhu2** [comment]
> Could we move the slider over to the left hand side like this? Just so it doesn't get confusing with two horizontal sliders. (PS. the icon isn't a necessity for now):

@WKFO, 2347203, moved with using `div` and `flex` containers, without icon. Unfortunately, I don't now how to SVG.

**Comment by orhun** [comment]
rec_20211202T155022


I'm having this issue while selecting a previous/next track. Player UI gets smaller and bigger based on the text I think (?). Can you look into this? @Cthulhu2

**Comment by Cthulhu2** [comment]
> Player UI gets smaller and bigger based on the text I think (?)

@orhun, I can't force align/justify items in `.metadata`. So fix 7840fb0 with using columns style and width.

**Comment by orhun** [comment]
I pushed 07cf696 for hiding the volume slider when it's not hovered. Just to make the player UI look less crowded...

**Review by orhun — APPROVED** [review]
Excellent job!

**Pull request merged**
